#pragma config(Sensor, port1,  outerSensorTop, sensorNone)
#pragma config(Sensor, port2,  outerSensorBottom, sensorNone)
#pragma config(Sensor, port3,  rampSensor,     sensorNone)
#pragma config(Sensor, port4,  lSwitchLeftFront, sensorDigitalIn)
#pragma config(Sensor, port5,  lSwitchLeftBack, sensorDigitalIn)
#pragma config(Sensor, port6,  lSwitchRightFront, sensorDigitalIn)
#pragma config(Sensor, port7,  lSwitchRightBack, sensorDigitalIn)
#pragma config(Sensor, port8,  lSwitchBackLeft, sensorDigitalIn)
#pragma config(Sensor, port9,  lSwitchBackRight, sensorDigitalIn)
#pragma config(Motor,  motor1, motorLeftWheel, tmotorNone, openLoop)
#pragma config(Motor,  motor2, motorRightWheel, tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define WHEEL_DIAMETER_IN_CM
#define WHEEL_DISTANCE_IN_CM
#define LONG_IR_MIN_ANALOG 400
#define LONG_IR_MAX_ANALOG 2700

float analogToDistanceLongIR(int analog);
bool detectedBallOrRobot();

/*
Converts analog reading from IR sensor into distance in cm.
@param analog: analog reading from the pin
@return distance: distance in cm from ir to object
*/

float analogToDistanceLongIR(int analog)
{
	float distance;
	//Covert the analog to distance;
	return distance;
}

/*
Checks if input value is within a certain range
@param value: value to check
@param min: min value of range
@param max: max value of range
@return bool: true if within range, false if not
*/

bool checkWithinRange(float value, float min, float max)
{
	return value <= min || value >= max ?  false : true;
}

bool detectedBallOrRobot()
{
	float outerSensorBottomDistance = analogToDistanceLongIR(SensorValue(outerSensorBottom));
	float outerSensorTopDistance = analogToDistanceLongIR(SensorValue(outerSensorTop));
	if (checkWithinRange(outerSensorBottom, LONG_IR_MIN_ANALOG, LONG_IR_MAX_ANALOG))
	{
		return false;
	}
}

task main()
{



}
